### ISSUE TITLE
Brakuje Gmail, Yahoo, Outlook

### ISSUE THREAD

**Issue by mik-laj** [ad-m/dwa-skladniki#7]
Witam

Brakuje usług Gmail, Yahoo, Outlook. Są to największe usługi zagraniczne, które mają popularność w Polsce., a więc warto się do nich porównywać.

Z wyrażami szacunku

**Comment by ad-m** [comment]
Yahoo nie wspiera kryterium polskości. G^Mail i Outlook zostaną dodane.
